### ISSUE TITLE
Interest reference rate is wrong

### ISSUE THREAD

**Issue by haliumsolutions** [gsteel/dont-pay-late#127]
I believe the legislation states that the interest rate is based on the reference rate for the 6 month periods 1st Jan to 30th June, and 1st July to 31st December - the rate is the one in force on the last day of the preceding period.

At the moment the rate seems to be as of the end of the previous month, which I believe to be incorrect - it should be as of the 30th June (until January when it then becomes the rate as of 31st December)

https://www.legislation.gov.uk/uksi/2002/1675/article/4/made

The reference BoE rate for today (30th Nov) should therefore be 1.25% and that plus the 8% makes it 9.25% not the 10.25% shown ?

Unless I'm missing something? :)

**Comment by gsteel** [comment]
Thanks for the report and the link @haliumsolutions - at the moment, it uses whatever reference rate is in effect at the invoice date, so I'll read up on that and make the necessary changes when time allows 👍

**Comment by mmulqueen** [comment]
If anyone else is looking for more information on this, the government published this user guide in 2014 https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/360834/bis-14-1116-a-users-guide-to-the-recast-late-payment-directive.pdf and it seems to have more detail than the current page on GOV.UK, I can't say whether it's still valid.

The government's Small Business Commissioner's own calculator gets this even more wrong, it seems to be using today's BoE rate regardless of when the interest started (inspect to see their JavaScript). Oops! https://www.smallbusinesscommissioner.gov.uk/deal-with-an-unpaid-invoice/how-to-chase-an-unpaid-invoice/interest-calculator/

**Comment by gsteel** [comment]
Thanks very much for the additional information @mmulqueen - I've finally got around to fixing this issue. The fix will be available on the site when I release 2.4.0 👍
